### ISSUE TITLE
Session store not set on request

### ISSUE THREAD

**Issue by daugaard47** [RhysLees/nova-impersonating-banner#2]
I keep receiving this error message in my logs. It only happens when I'm Logged In and NOT in impersonation mode.
When I'm a guest (Not Logged In) ..or.. Logged in and In Impersonation Mode I do not receive the error.

Any idea how to fix this? Should mention I'm not using Jet Stream. I'm using Laravel 9, Nova 4, PHP version 8.1

**Full StackTrace:**

```
	Session store not set on request. {"view":{"view":"/var/www/mysite/resources/views/layouts/app.blade.php","data":[]},"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): Session store not set on request. at /var/www/mysite/vendor/laravel/framework/src/Illuminate/Http/Request.php:558)
[stacktrace]
#0 /var/www/mysite/vendor/laravel/nova/src/Auth/Adapters/SessionImpersonator.php(88): Illuminate\\Http\\Request->session()
#1 /var/www/mysite/vendor/rhyslees/nova-impersonating-banner/src/Livewire/NovaImpersonatingBanner.php(18): Laravel\\Nova\\Auth\\Adapters\\SessionImpersonator->impersonating()
#2 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): RhysLees\\NovaImpersonatingBanner\\Livewire\\NovaImpersonatingBanner->mount()
#3 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /var/www/mysite/vendor/livewire/livewire/src/LifecycleManager.php(114): Illuminate\\Container\\BoundMethod::call()
#7 /var/www/mysite/vendor/livewire/livewire/src/LivewireManager.php(107): Livewire\\LifecycleManager->mount()
#8 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Livewire\\LivewireManager->mount()
#9 /var/www/mysite/resources/views/layouts/app.blade.php(6): Illuminate\\Support\\Facades\\Facade::__callStatic()
#10 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(109): require('...')
#11 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(110): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#12 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#13 /var/www/mysite/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(69): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#14 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#15 /var/www/mysite/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Illuminate\\View\\Engines\\CompilerEngine->get()
#16 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\LivewireViewCompilerEngine->get()
#17 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#18 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#19 /var/www/mysite/resources/views/errors/404.blade.php(169): Illuminate\\View\\View->render()
#20 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(109): require('...')
#21 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(110): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#22 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#23 /var/www/mysite/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(69): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#24 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#25 /var/www/mysite/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Illuminate\\View\\Engines\\CompilerEngine->get()
#26 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\LivewireViewCompilerEngine->get()
#27 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#28 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#29 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#30 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#31 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\\Http\\Response->__construct()
#32 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\\Routing\\ResponseFactory->make()
#33 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(616): Illuminate\\Routing\\ResponseFactory->view()
#34 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(541): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()
#35 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(447): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()
#36 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(366): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()
#37 /var/www/mysite/app/Exceptions/Handler.php(53): Illuminate\\Foundation\\Exceptions\\Handler->render()
#38 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(51): App\\Exceptions\\Handler->render()
#39 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(143): Illuminate\\Routing\\Pipeline->handleException()
#40 /var/www/mysite/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#42 /var/www/mysite/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle()
#44 /var/www/mysite/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()
#46 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#48 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#50 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#51 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#53 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#54 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#56 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#58 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#60 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#61 /var/www/mysite/public/index.php(56): Illuminate\\Foundation\\Http\\Kernel->handle()
#62 {main}

[previous exception] [object] (RuntimeException(code: 0): Session store not set on request. at /var/www/mysite/vendor/laravel/framework/src/Illuminate/Http/Request.php:558)
[stacktrace]
#0 /var/www/mysite/vendor/laravel/nova/src/Auth/Adapters/SessionImpersonator.php(88): Illuminate\\Http\\Request->session()
#1 /var/www/mysite/vendor/rhyslees/nova-impersonating-banner/src/Livewire/NovaImpersonatingBanner.php(18): Laravel\\Nova\\Auth\\Adapters\\SessionImpersonator->impersonating()
#2 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): RhysLees\\NovaImpersonatingBanner\\Livewire\\NovaImpersonatingBanner->mount()
#3 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#5 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#6 /var/www/mysite/vendor/livewire/livewire/src/LifecycleManager.php(114): Illuminate\\Container\\BoundMethod::call()
#7 /var/www/mysite/vendor/livewire/livewire/src/LivewireManager.php(107): Livewire\\LifecycleManager->mount()
#8 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Livewire\\LivewireManager->mount()
#9 /var/www/mysite/storage/framework/views/92a8a21a5a218edd09cf207cede0322d66907a27.php(8): Illuminate\\Support\\Facades\\Facade::__callStatic()
#10 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(109): require('...')
#11 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(110): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#12 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#13 /var/www/mysite/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(69): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#14 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#15 /var/www/mysite/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Illuminate\\View\\Engines\\CompilerEngine->get()
#16 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\LivewireViewCompilerEngine->get()
#17 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#18 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#19 /var/www/mysite/storage/framework/views/a119c0923ac16cc5537a7f41966e57c6b59f235b.php(225): Illuminate\\View\\View->render()
#20 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(109): require('...')
#21 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(110): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#22 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#23 /var/www/mysite/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(69): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#24 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Livewire\\LivewireViewCompilerEngine->evaluatePath()
#25 /var/www/mysite/vendor/livewire/livewire/src/ComponentConcerns/RendersLivewireComponents.php(35): Illuminate\\View\\Engines\\CompilerEngine->get()
#26 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/View.php(139): Livewire\\LivewireViewCompilerEngine->get()
#27 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#28 /var/www/mysite/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#29 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#30 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#31 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\\Http\\Response->__construct()
#32 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\\Routing\\ResponseFactory->make()
#33 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(616): Illuminate\\Routing\\ResponseFactory->view()
#34 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(541): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()
#35 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(447): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()
#36 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(366): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()
#37 /var/www/mysite/app/Exceptions/Handler.php(53): Illuminate\\Foundation\\Exceptions\\Handler->render()
#38 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(51): App\\Exceptions\\Handler->render()
#39 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(143): Illuminate\\Routing\\Pipeline->handleException()
#40 /var/www/mysite/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#42 /var/www/mysite/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle()
#44 /var/www/mysite/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()
#46 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#48 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#50 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#51 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#53 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#54 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#56 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#58 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#60 /var/www/mysite/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#61 /var/www/mysite/public/index.php(56): Illuminate\\Foundation\\Http\\Kernel->handle()
#62 {main}
"}
```

**Comment by RhysLees** [comment]
@daugaard47 could you provide a repo where this happens, please?

I would believe it has something to do with middleware not setting the session as users are not logged in:
https://stackoverflow.com/questions/34449770/laravel-session-store-not-set-on-request

**Comment by daugaard47** [comment]
That SO question helped.
I had to add the following to my `protected $middleware` in Kernal.php
```
protected $middleware = [
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
];
```
Thank you for the help!

**Comment by RhysLees** [comment]
> dd the following to my `protected $middleware` in Kernal.php

No problem!
